export const COMPANY_NAME = 'NF MANAGER';
export const CURRENT_YEAR = '2020';
export const LOGIN_MSG = 'Por favor, faça o login';
export const EMAIL = 'Email';
export const PASSWORD = 'Senha';
export const REMEMBERME = 'Lembrar de mim';
export const LOGIN = 'Entrar';
export const MENU_HOME = 'Início';
export const MENU_NEW_NF = 'Nova NF';
export const MENU_NF = 'NFs'
export const MENU_CALENDAR = 'Calendário';
export const MENU_REPORTS = 'Relatórios';
export const MENU_PROFILE = 'Perfil';
export const MENU_HELP = 'Ajuda';
export const MENU_LOGGOUT = 'Sair';
